org: tigaron
service: train-checker-python
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}

functions:
  Station:
    handler: main.lambda_handler
    name: ${self:service}-Station-${sls:stage}
    description: Endpoint to check train schedule based on station
    memorySize: 1024
    timeout: 10
    events:
      - httpApi:
          path: /station/
          method: get
plugins:
  - serverless-python-requirements
  - serverless-offline
